### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by OlaKenji** [MarkelZ/pygame-render#1]
Hi (probably more proper to write it here)

I incorporated in your shader engine into the project (happy ville). For now, I simply only transformed the resulting screen into a texture and rendered with your default shader. It was very simple and easy to use! However, I notised that my FPS dropped to 1 if I rendered each sprite via the shader engine.

I looked through the code but didn't notice anything obvious, and your example 2 seem to be handling many sprites fine. Do you know what could be the reason? Could it be that texture_surface that is the bottle neck? At the moment, this is called every frame for each sprite, and the background spites are quite big in happy ville.

**Comment by MarkelZ** [comment]
Hi @OlaKenji I'll also copy here my reply from https://github.com/MarkelZ/pygame-light2d/issues/4

Yes, `surface_to_texture` is not meant to be used in every frame with large textures because the conversion from `Surface` to `Texture` is expensive. Instead, it's better not to use any pygame surfaces at all, and directly load the textures with `load_texture` and render them with `render`. You would need `surface_to_texture` only when you cannot avoid using pygame surfaces (for example because you need some specific pygame functionality).

I already checked out Happy Ville a while ago and it's really cool! I don't mind helping you increase the FPS but I would need more information about how you render stuff.

**Comment by OlaKenji** [comment]
Ah, okay I understand. I just call the surface_to_texture in the initialisation of the classes instead and that seems to fix the issue. I notised that I needed to change the following line in util.py to make the "blit" position consistent though:

at line 56 from
x, y = position
to 
x = position[0] * scale[0]
y = position[1] * scale[1]

**Comment by MarkelZ** [comment]
@OlaKenji Thanks for letting me know about it! When you do `render(texture, layer, position, ...)`, the position is given as the pixel coordinates in the target layer. 

I saw that in your game the native resolution and the screen resolution are different, and you upscale everything by a constant factor to stretch it to fit the screen and to get a nice pixelated effect. Since the target layer's coordinates (the screen) are different from the game's native coordinates, your fix would indeed make everything consistent.

Although the change should work, it seems a bit "hacky". Instead, I would recommend to render everything to a `Layer` object which has your game's native resolution. Then, you can render the layer to the screen by upscaling it. This should have a few benefits:
- All coordinates are 1 to 1 (pixel-perfect).
- Game should run faster because you're rendering to a smaller target.
- Applying post-processing effects in the future would be very easy.

It would be very similar to [`examples/example5.py`](https://github.com/MarkelZ/pygame-render/blob/main/examples/example5.py). Of course this is just a suggestion :)

**Comment by OlaKenji** [comment]
You are right, that is much better. Thank you! :D

btw, do you happen to know an easy way to flip/mirror a sprite/texture? Or do I simply have to calculate the appropriate vertex coordinates?

**Comment by MarkelZ** [comment]
@OlaKenji Yes! It's one of the arguments of `render` called `flip`. You can set `flip=(True, False)` to flip it horizontally. I added it in a recent update, 1.2.0, so if you don't see it maybe you need to download a newer version.

**Comment by OlaKenji** [comment]
ah, that's a great feature! I downloaded your most recent code and works perfectly.

**Comment by MarkelZ** [comment]
@OlaKenji Awesome, thank you so much for the feedback! I'll close the issue now because we fixed it, but feel free to open a new one if needed. Also, if you have any new feature ideas I'll be happy to hear about them :)
