### ISSUE TITLE
Issue: Fullscreen not functioning properly on Linux

### ISSUE THREAD

**Issue by henry-paschke** [MarkelZ/pygame-render#5]
**Description:**

Currently, when the screen size passed into the rendering engine is the same size as the monitor it is displayed on, there are different results on different platforms. On Windows, the window full screens as expected, but on Linux, the screen instead appears windowed and extends past the edges of the display, causing the user to be unable to see parts of the window.

**Steps to Reproduce:**

- Launch the rendering engine on a Linux system.
- Create a rendering engine using the monitor's dimensions (can be queried with pg.display.Info()).
- Observe that the window never becomes full screen as intended. Shortcuts such as F11 do not work either.

**Expected Behavior:**
Full screen mode should function consistently across different operating systems. Users on Linux should be able to enter fullscreen mode without encountering any issues, similar to the behavior observed on Windows.

**Proposed Solution:**
To address this issue, it is suggested to introduce a flag option in the engine class's initializer that allows users to specify their preferred fullscreen behavior. This flag would provide users with the flexibility to enable or disable fullscreen functionality based on their specific requirements.

**Additional Information:**
    Operating System: Ubuntu 23.10 and Fedora Workstation 39
    Reproducibility: Consistently reproducible

**Comment by MarkelZ** [comment]
Hey @krakengamedev thank you for the detailed feedback! I noticed the same behavior too on my Linux machine.

I implemented your solution on a new branch named `screen_flags` and it seems to work for me. It would be very useful if you could verify that it works for you too. You can follow these steps:

1. Uninstall `pygame-render`:
  ```sh
  pip3 uninstall pygame-render
  ```
2. Clone the branch:
  ```sh
  git clone -b screen_flags https://github.com/MarkelZ/pygame-render.git
  ```
3. Change the directory and install the package locally:
  ```sh
  cd pygame-render/
  pip3 install -e .
  ```
4. Run `example7.py`, which implements full screen.
  ```sh
  cd examples/
  python3 example7.py
  ```

You may need to install a package called `screeninfo` before running `example7.py`. I use this package to get the screen size to be able to fullscreen properly.

You can also try running the project that you're working on with the `fullscreen` flag:

```py
engine = RenderEngine(screen_width, screen_height, fullscreen=1, vsync=1)
```

I noticed that the fullscreened window would flicker unless vsync is enabled, so that's why the additional flag.

If it works for you too, could you also check if it still works on Windows? Also, if you have a Mac, I would appreciate it if you could check that too. I only have Linux so I can't do it myself.

Thanks again :)

**Comment by henry-paschke** [comment]
@MarkelZ Thank you so much for the solution! 
I just ran your example program in Windows and it works as intended. I don't have my Ubuntu machine with me at the moment, but I will let you know when I get a chance to test it.

**Comment by MarkelZ** [comment]
@krakengamedev Sounds good! I'll wait

**Comment by henry-paschke** [comment]
I'm getting an unusual error during installation with pip install -e . on Ubuntu 23.10.

ERROR: Project file: path-to-cwd/pygame-render has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.

I didn't get this error on windows, but I'm not sure how to resolve this.

**Comment by MarkelZ** [comment]
I'm pretty sure this is not related to the last changes I made.

To fix it, you can try to install the package in non-editable mode, by not passing the `-e` flag:

```sh
pip install .
```

If this doesn't work either, you can add an empty `setup.cfg` file and try again, since the error you're getting is complaining about a missing setup file.

Let me know how it goes :)

**Comment by MarkelZ** [comment]
Hey @krakengamedev I tried the changes on different systems and it seems to work. I will soon merge it with the main branch and publish it as version 1.2.3. Thanks again for your feedback!
